version: '2'
services:
  tile:
    restart: unless-stopped
    image: homme/openstreetmap-tiles:latest
    volumes:
      - '/var/lib/postgresql'
      - './import:/data'
      - './osm.xml:/usr/local/src/mapnik-style/osm.xml'
      - './inc/:/usr/local/src/mapnik-style/inc/'
      - './png/:/usr/local/src/mapnik-style/symbols/png/'
    ports:
      - '84:80'
    command: 'startdb startservices'
